# -*- coding: utf-8 -*-
"""CNN Breast Cancer - TechChallenge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m8UrQg3El3M-781d7HRCIFCvdlCB_RL3

# Detecção de câncer de mama em mamografias com CNN

Dataset público **CBIS-DDSM: Breast Cancer Image Dataset**

### Problema que será resolvido
Aprendizado Supervisionado

Modelo de **classificação binária de imagens de mamografia** capaz de estimar se uma mamografia associada a uma lesão apresenta diagnóstico:

- **0 — Benigno**
- **1 — Maligno**

A variável-alvo será construída a partir da coluna `pathology` dos arquivos CSV do CBIS-DDSM.

### Técnica utilizada

**Rede Neural Convolucional (CNN — Convolutional Neural Network)** construída com TensorFlow/Keras.

Uma CNN é adequada para esse problema porque aprende automaticamente padrões espaciais presentes nas imagens, como bordas, texturas, formatos e estruturas que podem estar associadas a alterações mamográficas.

### Fluxo do Algoritmo

1. Configuração do Google Colab e GPU.
2. Download do CBIS-DDSM.
3. Carregamento e exploração dos dados.
4. Limpeza e organização dos rótulos.
5. Associação dos registros dos CSVs às imagens JPEG.
6. Análise exploratória.
7. Separação entre treino, validação e teste.
8. Pipeline de pré-processamento das imagens.
9. Tratamento de desbalanceamento das classes.
10. Construção da CNN.
11. Treinamento.
12. Avaliação com Accuracy, Recall, Precision, F1-score, AUC e matriz de confusão.
13. Análise de falsos negativos.
14. Explicabilidade com Grad-CAM.
15. Discussão crítica sobre uso clínico e limitações.

# 1. Configuração do Google Colab

Antes de executar o notebook, no Google Colab acesse:

**Ambiente de execução → Alterar tipo de ambiente de execução → Acelerador de hardware → GPU**

A GPU reduz significativamente o tempo necessário para treinar a rede neural convolucional.
"""

# Importa a biblioteca TensorFlow, que será utilizada para criar, treinar e avaliar a rede neural.
import tensorflow as tf

# Exibe a versão do TensorFlow disponível no Google Colab.
print("Versão do TensorFlow:", tf.__version__)

# Solicita ao TensorFlow a lista de GPUs disponíveis no ambiente.
gpus = tf.config.list_physical_devices("GPU")

# Exibe as GPUs encontradas para confirmar se o Colab está utilizando aceleração por hardware.
print("GPUs disponíveis:", gpus)

# Verifica se nenhuma GPU foi encontrada.
if len(gpus) == 0:
    # Exibe um aviso caso o notebook esteja rodando somente em CPU.
    print("ATENÇÃO: nenhuma GPU foi detectada. Ative a GPU nas configurações do Google Colab.")
else:
    # Exibe uma confirmação quando pelo menos uma GPU estiver disponível.
    print("GPU detectada com sucesso.")

"""
# 2. Download do dataset CBIS-DDSM

O dataset utilizado é:

**CBIS-DDSM: Breast Cancer Image Dataset**  
Kaggle: `awsaf49/cbis-ddsm-breast-cancer-image-dataset`

O conjunto possui mamografias, imagens de regiões de interesse e arquivos CSV contendo informações clínicas e o diagnóstico anatomopatológico.

Utilizaremos o pacote oficial `kagglehub` para fazer o download diretamente no Google Colab.

> O dataset é pesado, o download pode levar alguns minutos.
"""

# Instala a biblioteca kagglehub no ambiente do Google Colab.
!pip install -q kagglehub

# Importa a biblioteca kagglehub para permitir o download de datasets hospedados no Kaggle.
import kagglehub

# Define o identificador do dataset exatamente como ele aparece no Kaggle.
KAGGLE_DATASET = "awsaf49/cbis-ddsm-breast-cancer-image-dataset"

# Define a pasta do Google Colab onde o dataset será salvo.
PASTA_DATASET = "/content/cbis_ddsm"

# Faz o download do dataset e extrai seus arquivos para a pasta definida acima.
dataset_path = kagglehub.dataset_download(
    KAGGLE_DATASET,
    output_dir=PASTA_DATASET
)

# Exibe o caminho final em que os arquivos foram disponibilizados.
print("Dataset disponível em:", dataset_path)

"""
## 2.1 Conferindo a estrutura baixada

O dataset contém duas pastas principais:

- `csv/`: metadados e diagnósticos.
- `jpeg/`: imagens convertidas para JPEG.

Esta célula verifica se essas pastas estão realmente disponíveis.
"""

# Importa o módulo os para manipular caminhos, diretórios e arquivos do sistema operacional.
import os

# Monta o caminho completo da pasta que contém os arquivos CSV.
CSV_DIR = os.path.join(dataset_path, "csv")

# Monta o caminho completo da pasta que contém as imagens JPEG.
JPEG_DIR = os.path.join(dataset_path, "jpeg")

# Verifica se a pasta de CSVs existe.
print("Pasta CSV existe?", os.path.exists(CSV_DIR))

# Verifica se a pasta das imagens JPEG existe.
print("Pasta JPEG existe?", os.path.exists(JPEG_DIR))

# Exibe alguns nomes de arquivos encontrados na pasta CSV para validar a estrutura.
print("Arquivos CSV:", sorted(os.listdir(CSV_DIR))[:20])

"""
# 3. Importação das bibliotecas

Importando as bibliotecas utilizadas para:

- manipulação de dados;
- leitura de imagens;
- visualização;
- divisão dos dados;
- cálculo de métricas;
- construção e treinamento da CNN.
"""

# Importa o módulo random para controlar operações aleatórias e permitir reprodutibilidade.
import random

# Importa o NumPy para cálculos numéricos e manipulação de arrays.
import numpy as np

# Importa o pandas para leitura, limpeza e análise dos arquivos CSV.
import pandas as pd

# Importa o matplotlib para criação de gráficos.
import matplotlib.pyplot as plt

# Importa a classe Image da biblioteca PIL para abrir e inspecionar imagens.
from PIL import Image

# Importa a função train_test_split para separar pacientes entre treino e validação.
from sklearn.model_selection import train_test_split

# Importa a função compute_class_weight para calcular pesos que compensam classes desbalanceadas.
from sklearn.utils.class_weight import compute_class_weight

# Importa a função accuracy_score para calcular a acurácia final.
from sklearn.metrics import accuracy_score

# Importa a função precision_score para calcular a precisão do modelo.
from sklearn.metrics import precision_score

# Importa a função recall_score para calcular o recall ou sensibilidade.
from sklearn.metrics import recall_score

# Importa a função f1_score para calcular o F1-score.
from sklearn.metrics import f1_score

# Importa a função roc_auc_score para calcular a área sob a curva ROC.
from sklearn.metrics import roc_auc_score

# Importa a função confusion_matrix para calcular a matriz de confusão.
from sklearn.metrics import confusion_matrix

# Importa a classe ConfusionMatrixDisplay para desenhar a matriz de confusão.
from sklearn.metrics import ConfusionMatrixDisplay

# Importa a função classification_report para apresentar métricas detalhadas por classe.
from sklearn.metrics import classification_report

# Importa a função roc_curve para calcular os pontos utilizados na curva ROC.
from sklearn.metrics import roc_curve

# Importa a função precision_recall_curve para calcular a curva Precision-Recall.
from sklearn.metrics import precision_recall_curve

# Importa a função average_precision_score para calcular a Average Precision.
from sklearn.metrics import average_precision_score

"""
# 4. Reprodutibilidade do experimento

Redes neurais usam inicializações e operações aleatórias.
A semente (seed) é um número usado para inicializar os geradores de números pseudoaleatórios do programa. Ela serve para tornar operações que envolvem aleatoriedade mais reproduzíveis.
Importante utilizar o mesmo valor sempre que quiser repetir o experimento em condições semelhantes.
"""

# Define um número fixo que será utilizado como semente das operações aleatórias.
SEED = 42

# Define a semente do módulo random.
random.seed(SEED)

# Define a semente do NumPy.
np.random.seed(SEED)

# Define a semente utilizada internamente pelo TensorFlow.
tf.random.set_seed(SEED)

# Exibe a semente utilizada no experimento.
print("Semente definida:", SEED)

"""
# 5. Carregamento dos arquivos CSV

Essa etapa serve para carregar e organizar as informações do dataset antes de trabalhar diretamente com as imagens.

O dataset CBIS-DDSM organiza os casos mamográficos em duas categorias principais de anormalidades: massas (mass) e calcificações (calc).

Essas alterações podem estar associadas tanto a diagnósticos benignos quanto malignos.

O dataset também fornece uma separação oficial entre conjuntos de treinamento e teste, permitindo avaliar o modelo em dados não utilizados durante seu treinamento.

Nesta etapa são carregados os arquivos CSV contendo informações clínicas e diagnósticas dos casos, além do arquivo dicom_info.csv, responsável por auxiliar na associação entre os registros dos exames e as respectivas imagens JPEG disponíveis no dataset.

Essa associação será necessária para criar os pares de imagem e rótulo utilizados no treinamento supervisionado da Rede Neural Convolucional."""

# Lê o arquivo que contém metadados das imagens e o relacionamento entre DICOM e JPEG.
dicom_df = pd.read_csv(os.path.join(CSV_DIR, "dicom_info.csv"))

# Lê os casos de massa utilizados no conjunto oficial de treinamento.
mass_train_df = pd.read_csv(os.path.join(CSV_DIR, "mass_case_description_train_set.csv"))

# Lê os casos de massa utilizados no conjunto oficial de teste.
mass_test_df = pd.read_csv(os.path.join(CSV_DIR, "mass_case_description_test_set.csv"))

# Lê os casos de calcificação utilizados no conjunto oficial de treinamento.
calc_train_df = pd.read_csv(os.path.join(CSV_DIR, "calc_case_description_train_set.csv"))

# Lê os casos de calcificação utilizados no conjunto oficial de teste.
calc_test_df = pd.read_csv(os.path.join(CSV_DIR, "calc_case_description_test_set.csv"))

# Exibe a quantidade de linhas e colunas do arquivo de metadados.
print("dicom_info.csv:", dicom_df.shape)

# Exibe a quantidade de linhas e colunas dos casos de massa de treinamento.
print("mass train:", mass_train_df.shape)

# Exibe a quantidade de linhas e colunas dos casos de massa de teste.
print("mass test:", mass_test_df.shape)

# Exibe a quantidade de linhas e colunas dos casos de calcificação de treinamento.
print("calc train:", calc_train_df.shape)

# Exibe a quantidade de linhas e colunas dos casos de calcificação de teste.
print("calc test:", calc_test_df.shape)

"""
## 5.1 Visualização inicial dos dados

A inspeção das primeiras linhas ajuda a identificar as variáveis disponíveis.

Entre as colunas importantes estão:

- `patient_id`: identificador do paciente;
- `breast_density`: densidade mamária;
- `left or right breast`: lado da mama;
- `image view`: incidência da mamografia;
- `abnormality type`: tipo de alteração;
- `assessment`: avaliação BI-RADS associada ao caso;
- `pathology`: diagnóstico anatomopatológico;
- `image file path`: caminho original da mamografia.
"""

# Configura o pandas para mostrar todas as colunas durante a exploração.
pd.set_option("display.max_columns", None)

# Exibe as cinco primeiras linhas dos casos de massa do conjunto de treinamento.
display(mass_train_df.head())

# Exibe as cinco primeiras linhas dos casos de calcificação do conjunto de treinamento.
display(calc_train_df.head())

"""
# 6. Organização dos quatro conjuntos de casos
---
Aqui estamos fazendo uma etapa de organização e padronização dos dados antes da análise e do treinamento. Separamos em 4 etapas.


mass_train_df   → massas de treino

mass_test_df    → massas de teste

calc_train_df   → calcificações de treino

calc_test_df    → calcificações de teste

---



Os quatro conjuntos de casos do CBIS-DDSM são organizados antes da análise. Originalmente, os casos de massas e calcificações estão separados em arquivos distintos de treinamento e teste. Para preservar a origem de cada registro após a união das bases, são criadas duas colunas auxiliares. A coluna tipo_lesao identifica se o registro corresponde a uma massa ou calcificação, enquanto a coluna split_oficial informa se o exemplo pertence ao conjunto oficial de treinamento ou teste do dataset.

Antes das alterações, é criada uma cópia de cada DataFrame utilizando o método copy(), evitando modificações indesejadas nos objetos originais. Após a inclusão das novas informações, os quatro DataFrames são concatenados utilizando a função pd.concat(), resultando em um único DataFrame chamado casos_df. O parâmetro ignore_index=True reorganiza os índices da nova tabela de forma sequencial. Essa estratégia facilita as próximas etapas de exploração, limpeza e preparação dos dados, mantendo ao mesmo tempo as informações sobre o tipo de lesão e a divisão original entre treinamento e teste.

Nessa etapa ainda não estamos misturando treino e teste para treinar o modelo. Estamos apenas colocando os registros em uma tabela única para facilitar a manipulação. A coluna split_oficial será usada posteriormente justamente para separá-los novamente de forma correta."""

# Cria uma cópia independente do DataFrame de massas de treinamento.
mass_train_df = mass_train_df.copy()

# Registra que essas linhas representam casos de massa.
mass_train_df["tipo_lesao"] = "MASSA"

# Registra que essas linhas pertencem ao conjunto oficial de treinamento.
mass_train_df["split_oficial"] = "TRAIN"

# Cria uma cópia independente do DataFrame de massas de teste.
mass_test_df = mass_test_df.copy()

# Registra que essas linhas representam casos de massa.
mass_test_df["tipo_lesao"] = "MASSA"

# Registra que essas linhas pertencem ao conjunto oficial de teste.
mass_test_df["split_oficial"] = "TEST"

# Cria uma cópia independente do DataFrame de calcificações de treinamento.
calc_train_df = calc_train_df.copy()

# Registra que essas linhas representam casos de calcificação.
calc_train_df["tipo_lesao"] = "CALCIFICACAO"

# Registra que essas linhas pertencem ao conjunto oficial de treinamento.
calc_train_df["split_oficial"] = "TRAIN"

# Cria uma cópia independente do DataFrame de calcificações de teste.
calc_test_df = calc_test_df.copy()

# Registra que essas linhas representam casos de calcificação.
calc_test_df["tipo_lesao"] = "CALCIFICACAO"

# Registra que essas linhas pertencem ao conjunto oficial de teste.
calc_test_df["split_oficial"] = "TEST"

# Concatena os quatro DataFrames em uma única tabela.
casos_df = pd.concat(
    [mass_train_df, mass_test_df, calc_train_df, calc_test_df],
    ignore_index=True
)

# Exibe a quantidade total de registros e colunas após a concatenação.
print("Dimensão da base combinada:", casos_df.shape)

"""
# 7. Limpeza da variável-alvo
Aqui estamos fazendo uma etapa muito importante: preparar a variável que a CNN deverá aprender a prever.

É realizada a limpeza e padronização da variável-alvo utilizada pelo modelo. A coluna pathology contém o diagnóstico dos casos presentes no dataset. Como o objetivo do projeto é realizar uma classificação binária, os diagnósticos são organizados em duas classes: **benigno e maligno**. Os registros classificados como BENIGN_WITHOUT_CALLBACK também são considerados não malignos e, por esse motivo, são agrupados com a categoria BENIGN.

Inicialmente, os valores da coluna de diagnóstico são convertidos para texto, têm espaços extras removidos e são transformados em letras maiúsculas, garantindo uma representação padronizada das categorias. Em seguida, são mantidos apenas os registros cujo diagnóstico final seja BENIGN ou MALIGNANT.

Posteriormente, é criada a variável label, que representa numericamente o diagnóstico que deverá ser aprendido pela Rede Neural Convolucional. Os casos benignos recebem o valor 0, enquanto os casos malignos recebem o valor 1. Essa transformação é necessária porque os modelos de redes neurais trabalham com representações numéricas. Dessa forma, cada mamografia poderá ser associada ao seu respectivo rótulo durante o treinamento supervisionado da CNN.

O label é a resposta correta que a CNN tentará aprender a prever a partir da mamografia.
"""

# Exibe todas as categorias diferentes encontradas originalmente na coluna pathology.
print("Categorias originais:", casos_df["pathology"].value_counts(dropna=False))

# Remove espaços extras e converte os textos da coluna pathology para letras maiúsculas.
casos_df["pathology_clean"] = casos_df["pathology"].astype(str).str.strip().str.upper()

# Substitui BENIGN_WITHOUT_CALLBACK por BENIGN para transformar o problema em classificação binária.
casos_df["pathology_clean"] = casos_df["pathology_clean"].replace(
    {"BENIGN_WITHOUT_CALLBACK": "BENIGN"}
)

# Mantém somente linhas cujo diagnóstico final seja BENIGN ou MALIGNANT.
casos_df = casos_df[
    casos_df["pathology_clean"].isin(["BENIGN", "MALIGNANT"])
].copy()

# Cria a variável-alvo numérica: MALIGNANT recebe 1 e BENIGN recebe 0.
casos_df["label"] = (casos_df["pathology_clean"] == "MALIGNANT").astype(int)

# Exibe a distribuição das classes após a limpeza.
print(casos_df["pathology_clean"].value_counts())

# Exibe a distribuição numérica que será utilizada pelo modelo.
print(casos_df["label"].value_counts())

# O label é a resposta correta que a CNN tentará aprender a prever a partir da mamografia.

"""Após a padronização da variável pathology, foram identificados inicialmente 1.457 registros malignos, 1.429 registros benignos e 682 registros classificados como BENIGN_WITHOUT_CALLBACK. Como esta última categoria também representa um diagnóstico não maligno, seus registros foram agrupados à classe benigna. Dessa forma, a base passou a possuir 2.111 registros benignos e 1.457 malignos. Em seguida, as classes foram convertidas para representação numérica, atribuindo-se o valor 0 aos casos benignos e 1 aos casos malignos. Essa codificação será utilizada como variável-alvo durante o treinamento supervisionado da Rede Neural Convolucional. Observa-se também uma diferença na quantidade de exemplos entre as classes, fator que será considerado posteriormente durante o treinamento do modelo.

# 8. Análise exploratória dos dados

A Análise Exploratória de Dados, tem como objetivo compreender as principais características do conjunto de dados antes da etapa de modelagem. Essa análise permite identificar padrões, distribuições, possíveis desbalanceamentos entre as classes, valores ausentes e outras características que podem influenciar o treinamento do modelo.

Neste projeto, são analisadas características como a distribuição entre diagnósticos benignos e malignos, os tipos de lesão presentes nas mamografias, a lateralidade da mama, as incidências utilizadas nos exames, a densidade mamária e a presença de valores ausentes.

A primeira análise realizada corresponde à distribuição dos diagnósticos. Para isso, é utilizada a função value_counts() do pandas, responsável por contabilizar quantas ocorrências existem para cada categoria da coluna pathology_clean. Posteriormente, essas informações são representadas visualmente por meio de um gráfico de barras utilizando a biblioteca Matplotlib.

Essa análise permite observar a proporção entre casos benignos e malignos existentes no dataset. Após a padronização realizada anteriormente, foram identificados 2.111 registros benignos e 1.457 malignos. Portanto, existe uma maior quantidade de exemplos benignos. Embora a diferença não seja extremamente elevada, ela caracteriza um certo desbalanceamento entre as classes, que deverá ser considerado durante o treinamento da Rede Neural Convolucional.

A identificação desse desbalanceamento é importante porque modelos de Machine Learning podem apresentar tendência a favorecer classes que possuem maior quantidade de exemplos. Posteriormente, esse efeito será reduzido por meio da utilização de pesos de classe (class_weight), atribuindo pesos diferentes às classes durante o treinamento.
"""

# Calcula a quantidade de registros para cada diagnóstico.
contagem_diagnostico = casos_df["pathology_clean"].value_counts()

# Cria uma nova figura para o gráfico.
plt.figure(figsize=(7, 4))

# Desenha um gráfico de barras com a distribuição dos diagnósticos.
plt.bar(contagem_diagnostico.index, contagem_diagnostico.values)

# Define o título do gráfico.
plt.title("Distribuição dos diagnósticos")

# Define o texto do eixo horizontal.
plt.xlabel("Diagnóstico")

# Define o texto do eixo vertical.
plt.ylabel("Quantidade de registros")

# Exibe uma grade somente no eixo vertical para facilitar a leitura.
plt.grid(axis="y", alpha=0.3)

# Exibe o gráfico.
plt.show()

# Calcula a quantidade de registros por tipo de lesão.
contagem_lesao = casos_df["tipo_lesao"].value_counts()

# Cria uma nova figura para o gráfico.
plt.figure(figsize=(7, 4))

# Desenha um gráfico de barras para comparar massas e calcificações.
plt.bar(contagem_lesao.index, contagem_lesao.values)

# Define o título do gráfico.
plt.title("Distribuição dos tipos de lesão")

# Define o rótulo do eixo horizontal.
plt.xlabel("Tipo de lesão")

# Define o rótulo do eixo vertical.
plt.ylabel("Quantidade de registros")

# Exibe uma grade horizontal.
plt.grid(axis="y", alpha=0.3)

# Exibe o gráfico.
plt.show()

# Calcula a quantidade de registros por lateralidade da mama.
contagem_lado = casos_df["left or right breast"].value_counts()

# Cria uma nova figura.
plt.figure(figsize=(7, 4))

# Desenha o gráfico de barras da lateralidade.
plt.bar(contagem_lado.index, contagem_lado.values)

# Define o título do gráfico.
plt.title("Distribuição por lateralidade")

# Define o nome do eixo horizontal.
plt.xlabel("Mama")

# Define o nome do eixo vertical.
plt.ylabel("Quantidade de registros")

# Exibe uma grade horizontal.
plt.grid(axis="y", alpha=0.3)

# Exibe o gráfico.
plt.show()

# Calcula a quantidade de registros por incidência mamográfica.
contagem_view = casos_df["image view"].value_counts()

# Cria uma nova figura.
plt.figure(figsize=(7, 4))

# Desenha um gráfico de barras para as incidências disponíveis.
plt.bar(contagem_view.index, contagem_view.values)

# Define o título do gráfico.
plt.title("Distribuição das incidências mamográficas")

# Define o texto do eixo horizontal.
plt.xlabel("Incidência")

# Define o texto do eixo vertical.
plt.ylabel("Quantidade de registros")

# Exibe uma grade horizontal.
plt.grid(axis="y", alpha=0.3)

# Exibe o gráfico.
plt.show()

# Conta quantos registros existem para cada categoria de densidade mamária.
contagem_densidade = casos_df["breast_density"].value_counts().sort_index()

# Cria uma nova figura.
plt.figure(figsize=(7, 4))

# Desenha um gráfico de barras da densidade mamária.
plt.bar(contagem_densidade.index.astype(str), contagem_densidade.values)

# Define o título do gráfico.
plt.title("Distribuição da densidade mamária")

# Define o texto do eixo horizontal.
plt.xlabel("Categoria de densidade")

# Define o texto do eixo vertical.
plt.ylabel("Quantidade de registros")

# Exibe uma grade horizontal.
plt.grid(axis="y", alpha=0.3)

# Exibe o gráfico.
plt.show()

"""Esse gráfico mostra como os exames do dataset estão distribuídos de acordo com a densidade mamária. Ele não representa diretamente se o câncer é benigno ou maligno; representa uma característica da composição da mama observada na mamografia.

O que é densidade mamária?

A mama é formada principalmente por dois tipos de tecido:

tecido adiposo, ou gordura;
tecido fibroglandular, formado por glândulas e tecido conjuntivo.

A densidade mamária indica quanto tecido fibroglandular existe em relação à quantidade de gordura.

**Mais gordura -> menor densidade**

**Mais tecido fibroglandular -> maior densidade**

## 8.1 Valores ausentes

Nem toda coluna precisa ser utilizada pela CNN, pois a entrada principal do modelo será a imagem. Mesmo assim, analisar valores ausentes é importante para documentar a qualidade da base e atender à etapa de exploração e limpeza.
"""

# Calcula quantos valores ausentes existem em cada coluna.
valores_ausentes = casos_df.isna().sum()

# Ordena as colunas da maior para a menor quantidade de valores ausentes.
valores_ausentes = valores_ausentes.sort_values(ascending=False)

# Mantém somente as colunas que realmente possuem pelo menos um valor ausente.
valores_ausentes = valores_ausentes[valores_ausentes > 0]

# Exibe as quinze colunas com maior quantidade de valores ausentes.
display(valores_ausentes.head(15).to_frame("quantidade_ausente"))

"""Os valores ausentes encontrados em atributos descritivos, como características específicas de massa ou calcificação, não impedem o treinamento da CNN proposta, porque a entrada do modelo é a própria imagem e o rótulo é obtido da coluna `pathology`.

Entretanto, registros sem diagnóstico válido ou sem imagem correspondente serão removidos, pois esses dois elementos são indispensáveis para o aprendizado supervisionado.

## 8.2 Estatísticas descritivas e análise de correlação

As estatísticas descritivas são utilizadas para resumir as principais características das variáveis numéricas do dataset, apresentando informações como quantidade de registros, média, desvio-padrão, valores mínimos, máximos e quartis.

Já a análise de correlação avalia o grau de associação linear entre as variáveis utilizando o coeficiente de Pearson, que varia entre -1 e +1. Valores próximos de +1 indicam associação positiva, valores próximos de -1 indicam associação negativa e valores próximos de zero representam pouca relação linear.

Neste projeto, a correlação é utilizada somente como ferramenta de análise exploratória dos metadados e não como entrada da Rede Neural Convolucional.

Além disso, uma correlação observada não implica relação de causa e efeito.
"""

# Define as variáveis numéricas que serão utilizadas na análise descritiva.
colunas_numericas = [
    "breast_density",
    "assessment",
    "subtlety",
    "label"
]

# Seleciona somente as colunas numéricas definidas acima.
dados_numericos = casos_df[
    colunas_numericas
].copy()

# Exibe estatísticas como média, desvio-padrão, mínimo, quartis e máximo.
display(
    dados_numericos.describe().T
)

# Calcula a matriz de correlação de Pearson entre as variáveis numéricas selecionadas.
matriz_correlacao = dados_numericos.corr(
    method="pearson"
)

# Exibe os valores numéricos da matriz de correlação arredondados para três casas decimais.
display(
    matriz_correlacao.round(3)
)

# Cria uma figura para representar visualmente a matriz de correlação.
plt.figure(figsize=(7, 6))

# Exibe a matriz como uma imagem colorida, em que cada célula representa uma correlação.
plt.imshow(
    matriz_correlacao,
    vmin=-1,
    vmax=1,
    cmap="coolwarm"
)

# Adiciona uma barra lateral que representa a escala das correlações.
plt.colorbar(
    label="Correlação de Pearson"
)

# Define as posições dos rótulos do eixo horizontal.
plt.xticks(
    range(len(colunas_numericas)),
    colunas_numericas,
    rotation=45,
    ha="right"
)

# Define as posições dos rótulos do eixo vertical.
plt.yticks(
    range(len(colunas_numericas)),
    colunas_numericas
)

# Percorre as linhas da matriz para escrever o valor de cada correlação no gráfico.
for linha in range(len(colunas_numericas)):
    # Percorre as colunas da matriz.
    for coluna in range(len(colunas_numericas)):
        # Escreve o valor numérico no centro de cada célula.
        plt.text(
            coluna,
            linha,
            f"{matriz_correlacao.iloc[linha, coluna]:.2f}",
            ha="center",
            va="center"
        )

# Define o título do gráfico.
plt.title("Matriz de correlação dos metadados numéricos")

# Ajusta automaticamente as margens da figura.
plt.tight_layout()

# Exibe o gráfico.
plt.show()

"""A matriz deve ser interpretada como uma análise exploratória dos metadados. O campo `assessment`, por exemplo, representa uma avaliação associada à suspeita radiológica e pode apresentar relação com `label`. Entretanto, o modelo deste EXTRA **não utiliza essas variáveis como entrada**: a CNN recebe somente os pixels da mamografia. Isso mantém o experimento centrado em Visão Computacional e evita que a rede “resolva” a tarefa usando informações clínicas já fortemente associadas ao diagnóstico.

# 9. Associação entre os registros dos CSVs e as imagens JPEG

Nesta etapa é feita a associação entre os registros dos arquivos CSV e as imagens JPEG das mamografias.

Os CSVs mantêm referências originalmente ligadas aos arquivos DICOM, enquanto o dicom_info.csv possui informações que permitem localizar as imagens JPEG correspondentes no dataset.

Para realizar essa ligação, é extraído um identificador de série (uid) tanto dos metadados quanto dos caminhos dos casos. Em seguida, é criado um dicionário que relaciona cada uid ao caminho absoluto da respectiva imagem JPEG.

Esse relacionamento permite conectar cada registro clínico e seu diagnóstico à mamografia correta, formando os pares imagem + rótulo que serão utilizados posteriormente no treinamento supervisionado da CNN.

Registros sem identificador válido ou sem imagem correspondente são removidos para garantir a consistência da base.
"""

# Seleciona somente os metadados classificados como mamografias completas.
full_mammo_df = dicom_df[
    dicom_df["SeriesDescription"] == "full mammogram images"
].copy()

# Extrai do caminho JPEG o identificador da série localizado logo após a pasta jpeg.
full_mammo_df["uid"] = full_mammo_df["image_path"].str.extract(
    r"jpeg/([^/]+)/"
)

# Troca o prefixo original CBIS-DDSM/jpeg pelo caminho real da pasta JPEG no Google Colab.
full_mammo_df["image_path_abs"] = full_mammo_df["image_path"].apply(
    lambda caminho: caminho.replace("CBIS-DDSM/jpeg", JPEG_DIR)
)

# Remove registros que por algum motivo não possuam UID ou caminho de imagem.
full_mammo_df = full_mammo_df.dropna(
    subset=["uid", "image_path_abs"]
).copy()

# Remove UIDs duplicados para garantir um relacionamento único entre UID e imagem.
full_mammo_df = full_mammo_df.drop_duplicates(
    subset=["uid"]
).copy()

# Cria um dicionário em que a chave é o UID e o valor é o caminho absoluto da imagem.
uid_para_imagem = full_mammo_df.set_index("uid")["image_path_abs"].to_dict()

# Extrai o identificador da série presente no caminho original da mamografia em cada registro de caso.
casos_df["uid"] = casos_df["image file path"].str.extract(
    r"/([^/]+)/[^/]+$"
)

# Usa o dicionário criado anteriormente para encontrar o caminho JPEG correspondente a cada caso.
casos_df["image_path_abs"] = casos_df["uid"].map(uid_para_imagem)

# Conta quantos registros conseguiram localizar uma mamografia JPEG.
qtd_com_imagem = casos_df["image_path_abs"].notna().sum()

# Conta quantos registros não conseguiram localizar uma mamografia JPEG.
qtd_sem_imagem = casos_df["image_path_abs"].isna().sum()

# Exibe a quantidade de registros com imagem encontrada.
print("Registros com imagem encontrada:", qtd_com_imagem)

# Exibe a quantidade de registros sem imagem correspondente.
print("Registros sem imagem encontrada:", qtd_sem_imagem)

"""
## 9.1 Tratamento de imagens repetidas

Uma mesma mamografia pode aparecer mais de uma vez nos CSVs porque uma imagem pode possuir mais de uma anormalidade anotada.

Não devemos enviar a mesma imagem repetidamente ao modelo como se fossem imagens independentes.

Por isso, vamos agrupar registros pelo UID da mamografia. Se pelo menos uma anormalidade daquela imagem for maligna, a imagem será considerada maligna.
"""

# Remove registros que não conseguiram ser associados a uma imagem JPEG.
casos_com_imagem_df = casos_df.dropna(
    subset=["uid", "image_path_abs"]
).copy()

# Agrupa as linhas pela mamografia, paciente e divisão oficial.
imagens_df = casos_com_imagem_df.groupby(
    ["uid", "patient_id", "split_oficial", "image_path_abs"],
    as_index=False
).agg(
    # Se qualquer anormalidade da imagem for maligna, o rótulo final da imagem será 1.
    label=("label", "max"),
    # Une os tipos de lesão diferentes encontrados na mesma mamografia.
    tipo_lesao=("tipo_lesao", lambda valores: ", ".join(sorted(set(valores)))),
    # Mantém a maior densidade registrada caso exista mais de uma linha para a mesma imagem.
    breast_density=("breast_density", "max")
)

# Cria novamente uma coluna textual de diagnóstico a partir do rótulo agregado.
imagens_df["diagnostico"] = imagens_df["label"].map(
    {0: "BENIGN", 1: "MALIGNANT"}
)

# Verifica fisicamente se o arquivo de imagem realmente existe no armazenamento do Colab.
imagens_df["arquivo_existe"] = imagens_df["image_path_abs"].apply(
    os.path.exists
)

# Exibe quantos arquivos realmente existem.
print(imagens_df["arquivo_existe"].value_counts())

# Mantém somente registros cujo arquivo JPEG foi encontrado.
imagens_df = imagens_df[
    imagens_df["arquivo_existe"]
].copy()

# Remove a coluna auxiliar porque ela não será mais necessária.
imagens_df = imagens_df.drop(
    columns=["arquivo_existe"]
)

# Reinicia o índice do DataFrame após as remoções.
imagens_df = imagens_df.reset_index(drop=True)

# Exibe a quantidade final de mamografias utilizáveis.
print("Quantidade final de mamografias:", len(imagens_df))

# Exibe a distribuição das classes no nível da imagem.
print(imagens_df["diagnostico"].value_counts())

"""
# 10. Visualização de exemplos de mamografias

Nesta etapa são selecionados exemplos reais de mamografias benignas e malignas para inspeção visual.

O código escolhe aleatoriamente até três imagens de cada classe, utilizando o label para separar os casos benignos (0) dos malignos (1). Em seguida, essas amostras são reunidas em um único DataFrame e exibidas em uma grade de imagens.

Cada mamografia é aberta com a biblioteca PIL, convertida para escala de cinza e apresentada com seu respectivo diagnóstico. Essa visualização tem como objetivo validar se o pipeline está acessando corretamente as mamografias completas e não máscaras, regiões de interesse ou imagens recortadas.

Além disso, permite uma primeira inspeção visual das diferenças entre as classes antes do treinamento da Rede Neural Convolucional.
"""

# Seleciona até três imagens benignas aleatoriamente.
amostras_benignas = imagens_df[
    imagens_df["label"] == 0
].sample(
    n=min(3, (imagens_df["label"] == 0).sum()),
    random_state=SEED
)

# Seleciona até três imagens malignas aleatoriamente.
amostras_malignas = imagens_df[
    imagens_df["label"] == 1
].sample(
    n=min(3, (imagens_df["label"] == 1).sum()),
    random_state=SEED
)

# Concatena as amostras benignas e malignas em um único DataFrame.
amostras_visualizacao = pd.concat(
    [amostras_benignas, amostras_malignas],
    ignore_index=True
)

# Cria uma figura larga para exibir as mamografias.
plt.figure(figsize=(15, 8))

# Percorre todas as imagens selecionadas.
for indice, linha in amostras_visualizacao.iterrows():
    # Abre a imagem usando a biblioteca PIL.
    imagem = Image.open(linha["image_path_abs"])

    # Converte a imagem para escala de cinza.
    imagem = imagem.convert("L")

    # Cria uma posição dentro da grade de gráficos.
    plt.subplot(2, 3, indice + 1)

    # Exibe a mamografia em tons de cinza.
    plt.imshow(imagem, cmap="gray")

    # Exibe o diagnóstico associado à imagem.
    plt.title(linha["diagnostico"])

    # Remove os eixos para destacar apenas a imagem.
    plt.axis("off")

# Ajusta automaticamente os espaços entre as imagens.
plt.tight_layout()

# Exibe a figura completa.
plt.show()

"""
# 11. Análise das dimensões originais das imagens

Nesta etapa são analisadas as dimensões originais das mamografias para entender a resolução das imagens antes do treinamento.

Como mamografias possuem resolução elevada e podem apresentar tamanhos diferentes, o código seleciona uma amostra de até 200 imagens e registra a largura e a altura de cada uma.

Essas informações são armazenadas em um DataFrame e utilizadas para gerar estatísticas descritivas das dimensões.

A análise é importante porque redes neurais convolucionais exigem imagens com dimensões padronizadas para formar os lotes de treinamento.

Além disso, trabalhar com as imagens em resolução original consumiria muita memória e aumentaria significativamente o tempo de processamento no Google Colab.

Por esse motivo, posteriormente as mamografias serão redimensionadas para um tamanho menor e uniforme, buscando preservar o máximo possível das características visuais relevantes para a classificação.
"""

# Define o tamanho máximo da amostra utilizada para analisar as dimensões.
TAMANHO_AMOSTRA_DIMENSOES = min(200, len(imagens_df))

# Seleciona caminhos aleatórios sem alterar o DataFrame original.
caminhos_amostra = imagens_df["image_path_abs"].sample(
    n=TAMANHO_AMOSTRA_DIMENSOES,
    random_state=SEED
)

# Cria uma lista vazia para armazenar as larguras das imagens.
larguras = []

# Cria uma lista vazia para armazenar as alturas das imagens.
alturas = []

# Percorre cada caminho selecionado.
for caminho in caminhos_amostra:
    # Abre a imagem apenas durante esta iteração.
    with Image.open(caminho) as imagem:
        # Adiciona a largura da imagem à lista.
        larguras.append(imagem.width)

        # Adiciona a altura da imagem à lista.
        alturas.append(imagem.height)

# Cria um DataFrame com as dimensões coletadas.
dimensoes_df = pd.DataFrame(
    {"largura": larguras, "altura": alturas}
)

# Exibe estatísticas descritivas das dimensões.
display(dimensoes_df.describe())

"""As imagens serão redimensionadas para **256 × 256 pixels** usando `resize_with_pad`.

O `resize_with_pad` preserva a proporção original da mamografia e acrescenta preenchimento quando necessário, evitando deformar excessivamente a anatomia.

A redução para 256 × 256 torna o experimento viável no Colab, porém também é uma limitação: estruturas muito pequenas, especialmente microcalcificações, podem perder detalhes.

# 12. Separação entre treino, validação e teste

Nesta etapa, o conjunto de dados é separado em treino, validação e teste. O CBIS-DDSM já fornece uma divisão oficial entre treinamento e teste, e essa separação é preservada. A partir do conjunto oficial de treinamento, 20% dos pacientes são separados para formar o conjunto de validação. A divisão é feita por paciente, e não apenas por imagem, para evitar vazamento de dados, garantindo que imagens do mesmo paciente não apareçam simultaneamente em treino e validação.

A função train_test_split() realiza essa divisão, utilizando random_state=SEED para manter a reprodutibilidade e stratify para preservar aproximadamente a mesma proporção entre casos benignos e malignos nos conjuntos. Em seguida, são criados os DataFrames train_df, val_df e test_df, que representam respectivamente treinamento, validação e teste.

O conjunto de treino é utilizado para a CNN aprender e ajustar seus pesos. O conjunto de validação é utilizado durante o treinamento para acompanhar o desempenho do modelo em dados não utilizados diretamente no ajuste dos pesos, ajudando a identificar problemas como overfitting. Já o conjunto de teste permanece separado e é utilizado somente ao final para medir o desempenho real do modelo em dados não vistos.

O código também verifica se existem pacientes repetidos entre os conjuntos. O resultado esperado é zero, confirmando que não existe sobreposição de pacientes e reduzindo o risco de métricas artificialmente elevadas. Por fim, é analisada a distribuição das classes em treino, validação e teste, tanto em quantidade absoluta quanto em percentual, permitindo verificar se a proporção entre benignos e malignos foi preservada de forma adequada.

# **Treino é para aprender, validação é para acompanhar e ajustar o processo de treinamento, e teste é para avaliar o resultado final.**
"""

# Seleciona as imagens pertencentes ao conjunto oficial de treinamento.
train_pool_df = imagens_df[
    imagens_df["split_oficial"] == "TRAIN"
].copy()

# Seleciona as imagens pertencentes ao conjunto oficial de teste.
test_df = imagens_df[
    imagens_df["split_oficial"] == "TEST"
].copy()

# Agrupa os dados por paciente para criar uma tabela de pacientes únicos.
pacientes_df = train_pool_df.groupby(
    "patient_id",
    as_index=False
)["label"].max()

# Separa os identificadores de pacientes em treino e validação.
pacientes_treino, pacientes_validacao = train_test_split(
    pacientes_df["patient_id"],
    test_size=0.20,
    random_state=SEED,
    stratify=pacientes_df["label"]
)

# Mantém no treino somente imagens pertencentes aos pacientes selecionados para treino.
train_df = train_pool_df[
    train_pool_df["patient_id"].isin(pacientes_treino)
].copy()

# Mantém na validação somente imagens pertencentes aos pacientes selecionados para validação.
val_df = train_pool_df[
    train_pool_df["patient_id"].isin(pacientes_validacao)
].copy()

# Reinicia o índice do conjunto de treinamento.
train_df = train_df.reset_index(drop=True)

# Reinicia o índice do conjunto de validação.
val_df = val_df.reset_index(drop=True)

# Reinicia o índice do conjunto de teste.
test_df = test_df.reset_index(drop=True)

# Exibe a quantidade de imagens de treinamento.
print("Imagens de treino:", len(train_df))

# Exibe a quantidade de imagens de validação.
print("Imagens de validação:", len(val_df))

# Exibe a quantidade de imagens de teste.
print("Imagens de teste:", len(test_df))

# Calcula a interseção entre pacientes de treino e validação.
intersecao_train_val = set(train_df["patient_id"]) & set(val_df["patient_id"])

# Calcula a interseção entre pacientes de treino e teste.
intersecao_train_test = set(train_df["patient_id"]) & set(test_df["patient_id"])

# Exibe quantos pacientes aparecem simultaneamente em treino e validação.
print("Pacientes repetidos entre treino e validação:", len(intersecao_train_val))

# Exibe quantos pacientes aparecem simultaneamente em treino e teste.
print("Pacientes repetidos entre treino e teste oficial:", len(intersecao_train_test))

# Define uma função auxiliar para exibir a distribuição das classes em um conjunto.
def mostrar_distribuicao(nome, dataframe):
    # Calcula a quantidade de exemplos de cada classe.
    contagem = dataframe["diagnostico"].value_counts()

    # Calcula a proporção percentual de cada classe.
    percentual = dataframe["diagnostico"].value_counts(normalize=True).mul(100).round(2)

    # Exibe o nome do conjunto analisado.
    print(f"\n{nome}")

    # Exibe a contagem absoluta.
    print("Quantidade:")

    # Exibe os valores absolutos.
    print(contagem)

    # Exibe o percentual.
    print("Percentual:")

    # Exibe os percentuais calculados.
    print(percentual)

# Exibe a distribuição das classes no conjunto de treino.
mostrar_distribuicao("TREINO", train_df)

# Exibe a distribuição das classes no conjunto de validação.
mostrar_distribuicao("VALIDAÇÃO", val_df)

# Exibe a distribuição das classes no conjunto de teste.
mostrar_distribuicao("TESTE", test_df)

"""
# 13. Pipeline de pré-processamento das imagens

O pipeline fará as seguintes operações:

1. leitura do arquivo JPEG;
2. conversão para um canal em escala de cinza;
3. redimensionamento para 256 × 256 preservando proporção;
4. conversão para `float32`;
5. normalização dos pixels para o intervalo de 0 a 1;
6. criação de batches;
7. pré-carregamento dos próximos batches com `prefetch`.

A normalização é importante porque redes neurais treinam melhor quando as entradas possuem escala numérica controlada.


Nesta etapa é criado o pipeline de pré-processamento das mamografias, responsável por transformar as imagens originais em um formato adequado para serem utilizadas pela Rede Neural Convolucional. Cada arquivo JPEG é lido pelo TensorFlow e decodificado utilizando apenas um canal, pois as mamografias são imagens em escala de cinza. Em seguida, as imagens são redimensionadas para 256 × 256 pixels, garantindo que todas possuam o mesmo tamanho antes de serem enviadas para a CNN. O redimensionamento preserva a proporção da imagem para evitar deformações excessivas da anatomia.

Os valores dos pixels também são convertidos para o tipo float32 e normalizados para o intervalo entre 0 e 1. Originalmente, uma imagem JPEG normalmente possui pixels entre 0 e 255. A normalização coloca os dados em uma escala numérica menor e padronizada, facilitando o processo de otimização e tornando o treinamento da rede neural mais estável.

O parâmetro IMG_SIZE = 256 define a resolução utilizada pelo modelo, enquanto BATCH_SIZE = 16 determina que a rede processará grupos de 16 imagens por vez. Trabalhar com batches permite aproveitar melhor a memória e a capacidade de processamento da GPU sem carregar todo o dataset simultaneamente.

Por fim, o tf.data.AUTOTUNE permite que o TensorFlow ajuste automaticamente o paralelismo das operações, e o prefetch prepara os próximos batches enquanto a GPU processa o batch atual. Essas técnicas melhoram o desempenho do pipeline e reduzem o tempo em que a GPU fica aguardando o carregamento das próximas imagens."""

# Define a altura e a largura que todas as imagens terão durante o treinamento.
IMG_SIZE = 256

# Define quantas imagens serão processadas por vez pela rede neural.
BATCH_SIZE = 16

# Permite que o TensorFlow escolha automaticamente o melhor nível de paralelismo.
AUTOTUNE = tf.data.AUTOTUNE

# Cria uma função responsável por ler e pré-processar uma única imagem.
def carregar_imagem(caminho, rotulo):
    # Lê o arquivo JPEG diretamente do armazenamento.
    conteudo = tf.io.read_file(caminho)

    # Decodifica o JPEG utilizando apenas um canal, pois mamografias são imagens em escala de cinza.
    imagem = tf.io.decode_jpeg(conteudo, channels=1)

    # Converte os pixels inteiros de 0 a 255 para ponto flutuante no intervalo de 0 a 1.
    imagem = tf.image.convert_image_dtype(
        imagem,
        tf.float32
    )

    # Redimensiona a imagem preservando a proporção e adicionando preenchimento quando necessário.
    imagem = tf.image.resize_with_pad(
        imagem,
        target_height=IMG_SIZE,
        target_width=IMG_SIZE
    )

    # Converte o rótulo para ponto flutuante porque a saída sigmoid trabalha com valores contínuos.
    rotulo = tf.cast(
        rotulo,
        tf.float32
    )

    # Retorna a imagem processada e seu rótulo.
    return imagem, rotulo

# Cria uma função que transforma um DataFrame em um pipeline tf.data.
def criar_dataset(dataframe, treinamento=False):
    # Extrai os caminhos das imagens como um array.
    caminhos = dataframe["image_path_abs"].values

    # Extrai os rótulos e converte para float32.
    rotulos = dataframe["label"].values.astype("float32")

    # Cria um Dataset do TensorFlow contendo pares de caminho e rótulo.
    dataset = tf.data.Dataset.from_tensor_slices(
        (caminhos, rotulos)
    )

    # Verifica se o conjunto será utilizado no treinamento.
    if treinamento:
        # Embaralha as amostras para que a rede não aprenda a ordem dos dados.
        dataset = dataset.shuffle(
            buffer_size=len(dataframe),
            seed=SEED,
            reshuffle_each_iteration=True
        )

    # Aplica a função de leitura e pré-processamento a todas as imagens.
    dataset = dataset.map(
        carregar_imagem,
        num_parallel_calls=AUTOTUNE
    )

    # Agrupa as amostras em lotes para processamento pela GPU.
    dataset = dataset.batch(
        BATCH_SIZE
    )

    # Prepara lotes futuros enquanto o lote atual está sendo processado.
    dataset = dataset.prefetch(
        AUTOTUNE
    )

    # Retorna o pipeline completo.
    return dataset

# Cria o pipeline do conjunto de treinamento.
train_ds = criar_dataset(
    train_df,
    treinamento=True
)

# Cria o pipeline do conjunto de validação.
val_ds = criar_dataset(
    val_df,
    treinamento=False
)

# Cria o pipeline do conjunto de teste.
test_ds = criar_dataset(
    test_df,
    treinamento=False
)

"""
# 14. Data augmentation
Nesta etapa é aplicada a técnica de data augmentation, responsável por gerar pequenas variações artificiais das mamografias durante o treinamento da CNN. O objetivo é aumentar a diversidade dos exemplos apresentados ao modelo sem precisar adicionar novas imagens reais ao dataset. Isso ajuda a reduzir o overfitting, fazendo com que a rede não memorize apenas as imagens de treinamento e consiga generalizar melhor para imagens que nunca viu.

No projeto são utilizadas transformações leves e controladas, como espelhamento horizontal, pequena rotação, pequeno zoom e pequenas translações. Essas alterações são aplicadas aleatoriamente durante o treinamento, fazendo com que uma mesma mamografia possa aparecer de formas ligeiramente diferentes em épocas distintas.

O espelhamento horizontal inverte a imagem lateralmente, a rotação altera levemente seu ângulo, o zoom aproxima ou afasta discretamente a imagem e a translação desloca a mamografia alguns pixels nos eixos horizontal e vertical. Como se trata de imagens médicas, foram evitadas transformações agressivas para não distorcer a anatomia e criar padrões artificiais que não existiriam em uma mamografia real.

O data augmentation é implementado como um pequeno bloco sequencial do Keras e será incorporado à CNN. Ele atua apenas durante o treinamento, não sendo aplicado da mesma forma na validação ou no teste.
"""

# Cria um pequeno modelo sequencial responsável somente pelo data augmentation.
data_augmentation = tf.keras.Sequential(
    [
        # Espelha aleatoriamente a imagem no eixo horizontal.
        tf.keras.layers.RandomFlip(
            mode="horizontal"
        ),

        # Aplica uma rotação aleatória pequena.
        tf.keras.layers.RandomRotation(
            factor=0.03
        ),

        # Aplica um pequeno zoom aleatório.
        tf.keras.layers.RandomZoom(
            height_factor=0.05,
            width_factor=0.05
        ),

        # Desloca levemente a imagem nos eixos horizontal e vertical.
        tf.keras.layers.RandomTranslation(
            height_factor=0.03,
            width_factor=0.03
        ),
    ],
    # Define um nome para facilitar a identificação da camada no resumo do modelo.
    name="data_augmentation"
)

"""
# 15. Tratamento do desbalanceamento das classes

Em problemas médicos, é comum existir diferença na quantidade de exemplos de cada classe.

Se uma classe aparecer muito mais que a outra, o modelo pode aprender a favorecer a classe majoritária.

Para reduzir esse efeito, serão utilizados `class_weight`, atribuindo maior peso à classe menos frequente durante o treinamento.
"""

# Identifica as classes diferentes presentes no conjunto de treinamento.
classes = np.unique(
    train_df["label"]
)

# Calcula pesos automaticamente usando o critério balanced do scikit-learn.
pesos = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=train_df["label"]
)

# Converte os pesos calculados para o formato de dicionário esperado pelo Keras.
class_weight = {
    int(classe): float(peso)
    for classe, peso in zip(classes, pesos)
}

# Exibe os pesos que serão aplicados durante o treinamento.
print("Pesos das classes:", class_weight)

"""
# 16. Construção da Rede Neural Convolucional

Nesta etapa é construída a Rede Neural Convolucional responsável por analisar as mamografias e classificá-las como benignas ou malignas. A rede foi criada no formato sequencial do Keras, no qual as camadas são executadas uma após a outra. A entrada da CNN recebe imagens de 256 × 256 pixels com apenas um canal, pois as mamografias são utilizadas em escala de cinza. Antes das convoluções, o bloco de data augmentation aplica pequenas variações aleatórias nas imagens durante o treinamento para reduzir overfitting.

A rede possui quatro blocos convolucionais com 32, 64, 128 e 256 filtros. As camadas Conv2D são responsáveis por aprender características visuais das imagens, como bordas, texturas, contrastes e padrões mais complexos. Todas utilizam filtros de 3 × 3, função de ativação ReLU e padding="same", que preserva as dimensões espaciais durante a convolução. Conforme a rede se aprofunda, a quantidade de filtros aumenta, permitindo aprender uma quantidade maior de características.

Após cada convolução é utilizada uma camada BatchNormalization, que ajuda a estabilizar o treinamento, seguida de MaxPooling2D, responsável por reduzir as dimensões dos mapas de características. Dessa forma, a rede preserva informações importantes enquanto diminui progressivamente a quantidade de dados processados.

Depois dos blocos convolucionais é utilizado o GlobalAveragePooling2D, que transforma cada mapa de características em um único valor representativo. Em seguida, são utilizadas camadas Dropout, que desativam aleatoriamente parte das ativações durante o treinamento para reduzir overfitting. Uma camada Dense com 128 neurônios combina as características aprendidas e prepara a rede para a classificação final.

A camada de saída possui apenas um neurônio com função de ativação sigmoid. Como o problema é uma classificação binária, a sigmoid produz um valor entre 0 e 1, que pode ser interpretado como a probabilidade prevista de malignidade. Valores mais próximos de 0 indicam maior tendência para a classe benigna, enquanto valores próximos de 1 indicam maior tendência para a classe maligna.

## Arquitetura

Cada bloco convolucional possui:

1. `Conv2D`: aprende filtros e padrões visuais;
2. `BatchNormalization`: estabiliza o treinamento;
3. `MaxPooling2D`: reduz a dimensão espacial e retém características relevantes.

Ao final:

- `GlobalAveragePooling2D` resume os mapas de características;
- `Dense` combina as características aprendidas;
- `Dropout` reduz overfitting;
- a saída `sigmoid` produz a probabilidade de malignidade entre 0 e 1.

# As camadas convolucionais extraem características visuais da mamografia, o pooling reduz progressivamente a dimensionalidade, as camadas finais combinam as características aprendidas e a sigmoid retorna a probabilidade de a imagem pertencer à classe maligna.
"""

# Cria uma nova rede neural no formato sequencial.
model = tf.keras.Sequential(
    [
        # Define explicitamente o formato de entrada: 256 por 256 pixels e um canal.
        tf.keras.layers.Input(
            shape=(IMG_SIZE, IMG_SIZE, 1)
        ),

        # Aplica data augmentation apenas durante o treinamento.
        data_augmentation,

        # Cria a primeira camada convolucional com 32 filtros de tamanho 3x3.
        tf.keras.layers.Conv2D(
            filters=32,
            kernel_size=3,
            padding="same",
            activation="relu"
        ),

        # Normaliza as ativações do primeiro bloco convolucional.
        tf.keras.layers.BatchNormalization(),

        # Reduz pela metade aproximadamente a resolução espacial dos mapas de características.
        tf.keras.layers.MaxPooling2D(
            pool_size=2
        ),

        # Cria a segunda camada convolucional com 64 filtros.
        tf.keras.layers.Conv2D(
            filters=64,
            kernel_size=3,
            padding="same",
            activation="relu"
        ),

        # Normaliza as ativações do segundo bloco.
        tf.keras.layers.BatchNormalization(),

        # Reduz novamente a resolução espacial.
        tf.keras.layers.MaxPooling2D(
            pool_size=2
        ),

        # Cria a terceira camada convolucional com 128 filtros.
        tf.keras.layers.Conv2D(
            filters=128,
            kernel_size=3,
            padding="same",
            activation="relu"
        ),

        # Normaliza as ativações do terceiro bloco.
        tf.keras.layers.BatchNormalization(),

        # Reduz novamente a resolução espacial.
        tf.keras.layers.MaxPooling2D(
            pool_size=2
        ),

        # Cria uma quarta camada convolucional mais profunda com 256 filtros.
        tf.keras.layers.Conv2D(
            filters=256,
            kernel_size=3,
            padding="same",
            activation="relu"
        ),

        # Normaliza as ativações do quarto bloco.
        tf.keras.layers.BatchNormalization(),

        # Reduz os mapas de características pela última vez antes da classificação.
        tf.keras.layers.MaxPooling2D(
            pool_size=2
        ),

        # Converte cada mapa de características em um único valor médio.
        tf.keras.layers.GlobalAveragePooling2D(),

        # Desativa aleatoriamente 40% das ativações para reduzir overfitting.
        tf.keras.layers.Dropout(
            rate=0.40
        ),

        # Cria uma camada totalmente conectada com 128 neurônios.
        tf.keras.layers.Dense(
            units=128,
            activation="relu"
        ),

        # Desativa aleatoriamente 30% dos neurônios dessa camada durante o treinamento.
        tf.keras.layers.Dropout(
            rate=0.30
        ),

        # Cria a camada de saída com um único neurônio e função sigmoid.
        tf.keras.layers.Dense(
            units=1,
            activation="sigmoid"
        ),
    ],
    # Define um nome para o modelo.
    name="CNN_Mamografia_CBIS_DDSM"
)

# Exibe a arquitetura completa e a quantidade de parâmetros treináveis.
model.summary()

"""
# 17. Compilação do modelo

Nesta etapa é realizada a compilação do modelo, momento em que são definidos os principais elementos que irão orientar o treinamento da Rede Neural Convolucional. Como o problema possui duas classes, benigno e maligno, é utilizada a função de perda binary_crossentropy, responsável por medir a diferença entre a previsão feita pela rede e o valor correto do rótulo. Quanto maior essa diferença, maior será o erro calculado durante o treinamento.

O otimizador escolhido é o Adam, configurado com uma taxa de aprendizagem de 0.001. O Adam é responsável por atualizar os pesos da rede neural a partir dos erros calculados pela função de perda, permitindo que o modelo aprenda progressivamente com os dados. A taxa de aprendizagem controla o tamanho dos ajustes realizados nos pesos a cada etapa do treinamento.

Durante o treinamento, também são acompanhadas algumas métricas importantes. A Accuracy representa a proporção total de previsões corretas. O Recall, também chamado de sensibilidade, indica quantos casos realmente malignos foram identificados corretamente pelo modelo, sendo uma métrica especialmente importante neste problema devido ao risco associado aos falsos negativos. A Precision mede, entre os casos classificados como malignos, quantos realmente pertenciam à classe maligna. Já a AUC avalia a capacidade geral do modelo de diferenciar casos benignos de malignos em diferentes limiares de classificação. O F1-score será calculado posteriormente no conjunto de teste, combinando Precision e Recall em uma única métrica.



"""

# Cria o otimizador Adam com uma taxa de aprendizagem inicial de 0.001.
otimizador = tf.keras.optimizers.Adam(
    learning_rate=0.001
)

# Compila o modelo definindo a função de perda, o otimizador e as métricas.
model.compile(
    # Utiliza binary crossentropy porque o problema possui duas classes.
    loss="binary_crossentropy",

    # Utiliza o otimizador Adam definido acima.
    optimizer=otimizador,

    # Define as métricas monitoradas durante treino e validação.
    metrics=[
        # Mede a proporção total de previsões corretas.
        tf.keras.metrics.BinaryAccuracy(
            name="accuracy"
        ),

        # Mede a sensibilidade, isto é, quantos casos malignos foram corretamente identificados.
        tf.keras.metrics.Recall(
            name="recall"
        ),

        # Mede entre os casos previstos como malignos quantos realmente eram malignos.
        tf.keras.metrics.Precision(
            name="precision"
        ),

        # Mede a capacidade de separação das classes em vários limiares.
        tf.keras.metrics.AUC(
            name="auc"
        ),
    ]
)

"""
# 18. Callbacks

Nesta etapa são configurados os callbacks, que são mecanismos utilizados para controlar automaticamente o treinamento da Rede Neural Convolucional. Eles permitem acompanhar o comportamento do modelo e tomar decisões durante o treinamento sem necessidade de intervenção manual.

Serão utilizados:

- **EarlyStopping**: encerra o treinamento quando a validação deixa de melhorar;
- **ReduceLROnPlateau**: reduz a taxa de aprendizagem quando a perda de validação estagna;
- **ModelCheckpoint**: salva o melhor modelo encontrado.

Em resumo, os callbacks ajudam a tornar o treinamento mais eficiente e seguro: o EarlyStopping evita treinamento desnecessário e excesso de overfitting, o ReduceLROnPlateau ajusta a velocidade de aprendizagem quando o modelo para de evoluir e o ModelCheckpoint garante que a melhor versão do modelo seja preservada."""

# Define o caminho em que o melhor modelo será salvo.
CAMINHO_MELHOR_MODELO = "/content/melhor_modelo_cnn_mamografia.keras"

# Cria o callback de parada antecipada.
early_stopping = tf.keras.callbacks.EarlyStopping(
    # Monitora a AUC do conjunto de validação.
    monitor="val_auc",

    # Informa que valores maiores de AUC são melhores.
    mode="max",

    # Aguarda cinco épocas sem melhora antes de interromper.
    patience=5,

    # Restaura os pesos da melhor época ao final.
    restore_best_weights=True
)

# Cria o callback que reduz a taxa de aprendizagem quando a validação para de melhorar.
reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(
    # Monitora a perda de validação.
    monitor="val_loss",

    # Reduz a taxa de aprendizagem pela metade.
    factor=0.5,

    # Aguarda duas épocas sem melhora antes de reduzir.
    patience=2,

    # Impede que a taxa fique menor que este valor.
    min_lr=1e-6,

    # Exibe no console quando uma redução ocorrer.
    verbose=1
)

# Cria o callback que salva o melhor modelo.
checkpoint = tf.keras.callbacks.ModelCheckpoint(
    # Define o arquivo em que o modelo será salvo.
    filepath=CAMINHO_MELHOR_MODELO,

    # Monitora a AUC de validação.
    monitor="val_auc",

    # Informa que valores maiores são melhores.
    mode="max",

    # Salva somente quando houver um novo melhor resultado.
    save_best_only=True,

    # Exibe uma mensagem quando o modelo for salvo.
    verbose=1
)

"""
# 19. Treinamento da CNN

Nesta etapa é iniciado o treinamento da Rede Neural Convolucional. Foi definido um limite máximo de 30 épocas, sendo que cada época representa uma passagem completa por todo o conjunto de treinamento. Durante essas épocas, a CNN analisa as mamografias, realiza previsões, calcula os erros e ajusta seus pesos para tentar melhorar progressivamente seu desempenho.

O método model.fit() é responsável por executar esse treinamento. O conjunto train_ds é utilizado para o aprendizado propriamente dito, enquanto o val_ds é usado ao final de cada época para avaliar como o modelo está se comportando em dados que não participam diretamente do ajuste dos pesos. Isso permite acompanhar a capacidade de generalização da rede e identificar possíveis sinais de overfitting.

Também são aplicados os class_weight, que atribuem pesos diferentes às classes para compensar o desbalanceamento entre casos benignos e malignos. Dessa forma, o modelo não tende a favorecer apenas a classe que possui maior quantidade de exemplos.

Os callbacks definidos anteriormente também são ativados durante o treinamento. O EarlyStopping pode interromper o processo antes das 30 épocas caso a AUC de validação deixe de melhorar, o ReduceLROnPlateau reduz a taxa de aprendizagem quando necessário e o ModelCheckpoint salva automaticamente a melhor versão do modelo encontrada ao longo do treinamento.

Por fim, o resultado do treinamento é armazenado na variável history, que contém o histórico das métricas de cada época, como perda, Accuracy, Recall e AUC. Essas informações serão utilizadas posteriormente para gerar gráficos e analisar a evolução do aprendizado da CNN.
"""

# Define o número máximo de épocas de treinamento.
EPOCHS = 5

# Inicia o treinamento da rede neural.
history = model.fit(
    # Utiliza o pipeline de imagens de treinamento.
    train_ds,

    # Utiliza o conjunto de validação para acompanhar a generalização.
    validation_data=val_ds,

    # Define a quantidade máxima de épocas.
    epochs=EPOCHS,

    # Aplica os pesos calculados para compensar o desbalanceamento das classes.
    class_weight=class_weight,

    # Ativa os callbacks definidos anteriormente.
    callbacks=[
        early_stopping,
        reduce_lr,
        checkpoint
    ]
)

"""# **Resultado do treinamento**

Durante o treinamento experimental de cinco épocas, foi possível observar uma evolução gradual da Rede Neural Convolucional, embora as métricas de validação ainda tenham apresentado oscilações significativas nas primeiras épocas. Esse comportamento é esperado durante as etapas iniciais do aprendizado, quando os pesos da rede ainda estão sendo ajustados. Em alguns momentos, o modelo apresentou tendência de classificar grande parte das imagens em apenas uma classe, resultando, por exemplo, em Recall de 100% acompanhado de baixa Accuracy e Precision. Ao longo das épocas, entretanto, as métricas tornaram-se mais equilibradas. Na quinta época foi obtido o melhor resultado de validação, com Accuracy de aproximadamente 63,7%, Recall de 59,0%, Precision de 61,0% e AUC de 69,3%. O ModelCheckpoint identificou essa melhora e salvou automaticamente essa versão do modelo. Como foram utilizadas apenas cinco épocas para uma execução rápida de teste, esses resultados não devem ser considerados definitivos. Para o experimento final, será utilizado um número maior de épocas, mantendo mecanismos como EarlyStopping e ReduceLROnPlateau para controlar automaticamente o treinamento.

Obs: Um Recall de 1,0 não significa necessariamente um excelente modelo. Se ele disser que todas as mamografias são malignas, encontrará todos os cânceres, mas produzirá uma enorme quantidade de falsos positivos. É justamente por isso que estamos avaliando Recall, Precision, Accuracy e AUC em conjunto.

# 20. Curvas de aprendizagem

Os gráficos de treino e validação ajudam a identificar:

- **overfitting**: treino melhora enquanto validação piora;
- **underfitting**: ambos permanecem ruins;
- **boa generalização**: treino e validação evoluem de maneira consistente.

Nesta etapa são geradas as curvas de aprendizagem do modelo, utilizando o histórico armazenado na variável history durante o treinamento. Esses gráficos permitem comparar o desempenho da CNN nos conjuntos de treino e validação ao longo das épocas, ajudando a entender se o modelo está realmente aprendendo e se consegue generalizar para dados que não foram utilizados diretamente no ajuste dos pesos.

O primeiro gráfico compara a função de perda (loss) entre treino e validação. A perda representa o erro cometido pelo modelo. O comportamento esperado é que esse valor diminua ao longo das épocas. Se a perda de treinamento continuar caindo, mas a perda de validação começar a aumentar, pode ser um sinal de overfitting, indicando que a rede está ficando muito especializada nos dados de treino e piorando em dados novos.

O segundo gráfico acompanha a AUC dos conjuntos de treino e validação. A AUC indica a capacidade do modelo de diferenciar casos benignos de malignos. O objetivo é observar valores crescentes e relativamente próximos entre treino e validação. Se a AUC de treinamento ficar muito alta enquanto a de validação permanecer significativamente menor, isso também pode indicar overfitting.

O terceiro gráfico acompanha o Recall, ou sensibilidade. Essa métrica é especialmente importante neste projeto porque mostra a capacidade da CNN de identificar corretamente os casos realmente malignos. Ao comparar o Recall de treino com o de validação, é possível verificar se o modelo está aprendendo a detectar os casos malignos sem apresentar uma grande perda de desempenho quando recebe imagens que não utilizou diretamente para aprender.

De maneira geral, as curvas de aprendizagem permitem identificar três situações principais. No overfitting, o desempenho no treinamento continua melhorando enquanto o desempenho na validação começa a piorar. No underfitting, tanto treino quanto validação apresentam desempenho ruim, indicando que o modelo ainda não conseguiu aprender adequadamente os padrões dos dados. Já uma boa generalização ocorre quando as métricas de treino e validação apresentam evolução semelhante e resultados relativamente próximos.

Esses gráficos são importantes porque analisar apenas a métrica final do treinamento não é suficiente. As curvas permitem observar como o aprendizado ocorreu ao longo das épocas e ajudam a avaliar se o modelo está aprendendo padrões que podem ser aplicados a novas mamografias ou apenas memorizando os exemplos utilizados durante o treinamento.
"""

# Cria uma figura para comparar a perda de treino e validação.
plt.figure(figsize=(8, 5))

# Desenha a perda observada no conjunto de treinamento.
plt.plot(
    history.history["loss"],
    label="Treino"
)

# Desenha a perda observada no conjunto de validação.
plt.plot(
    history.history["val_loss"],
    label="Validação"
)

# Define o título do gráfico.
plt.title("Evolução da função de perda")

# Define o nome do eixo horizontal.
plt.xlabel("Época")

# Define o nome do eixo vertical.
plt.ylabel("Binary crossentropy")

# Exibe a legenda.
plt.legend()

# Exibe uma grade para facilitar a leitura.
plt.grid(alpha=0.3)

# Exibe o gráfico.
plt.show()

"""# **Interpretação do gráfico da função de perda**
O gráfico da função de perda apresenta a evolução do erro da CNN nos conjuntos de treinamento e validação ao longo das épocas. A perda do conjunto de treinamento apresentou redução gradual, indicando que o modelo estava aprendendo a partir das mamografias utilizadas no ajuste dos pesos. Entretanto, a perda de validação apresentou oscilações significativas nas primeiras épocas, demonstrando que o modelo ainda possuía dificuldade para generalizar o aprendizado para imagens não utilizadas diretamente no treinamento. Na última época ocorreu uma melhora expressiva da validação, com redução da perda para aproximadamente 0,64, ficando próxima da perda de treinamento. Como o experimento foi executado somente por cinco épocas para fins de teste, ainda não é possível concluir definitivamente sobre overfitting ou capacidade de generalização, sendo necessário um treinamento mais longo para uma análise mais consistente.
"""

# Cria uma figura para comparar a AUC de treino e validação.
plt.figure(figsize=(8, 5))

# Desenha a AUC observada no conjunto de treinamento.
plt.plot(
    history.history["auc"],
    label="Treino"
)

# Desenha a AUC observada no conjunto de validação.
plt.plot(
    history.history["val_auc"],
    label="Validação"
)

# Define o título do gráfico.
plt.title("Evolução da AUC")

# Define o nome do eixo horizontal.
plt.xlabel("Época")

# Define o nome do eixo vertical.
plt.ylabel("AUC")

# Exibe a legenda.
plt.legend()

# Exibe uma grade.
plt.grid(alpha=0.3)

# Exibe o gráfico.
plt.show()

"""# **Interpretação do gráfico de evolução da AUC**

**AUC** significa **Área Sob a Curva**. No nosso caso, estamos falando da área sob a curva ROC. **Ela mede o quanto o modelo consegue separar corretamente as duas classes, 0 - benigno e 1 - maligno.** A curva ROC (Receiver Operating Characteristic) é utilizada para avaliar o desempenho de um modelo de classificação considerando diferentes limiares de decisão. Ela relaciona a taxa de verdadeiros positivos, também conhecida como Recall ou Sensibilidade, com a taxa de falsos positivos.


---


**O gráfico de evolução da AUC demonstra a capacidade da Rede Neural Convolucional de diferenciar os casos benignos dos malignos ao longo das épocas de treinamento.** No conjunto de treino, observa-se uma tendência gradual de melhora, com a AUC aumentando de aproximadamente 0,54 para 0,64. No conjunto de validação, os valores apresentaram maior oscilação nas primeiras épocas, chegando a cair para aproximadamente 0,48, mas apresentaram uma melhora significativa na última época, atingindo cerca de 0,69. Esse foi o melhor resultado de validação obtido durante o experimento. Como o treinamento foi realizado com apenas cinco épocas para uma execução rápida, ainda não é possível concluir de forma definitiva sobre a estabilidade ou capacidade final de generalização do modelo. Entretanto, a evolução observada indica que a CNN começou a aprender características capazes de separar as classes benignas e malignas.
"""

# Cria uma figura para comparar o recall de treino e validação.
plt.figure(figsize=(8, 5))

# Desenha o recall observado no treinamento.
plt.plot(
    history.history["recall"],
    label="Treino"
)

# Desenha o recall observado na validação.
plt.plot(
    history.history["val_recall"],
    label="Validação"
)

# Define o título do gráfico.
plt.title("Evolução do Recall")

# Define o nome do eixo horizontal.
plt.xlabel("Época")

# Define o nome do eixo vertical.
plt.ylabel("Recall")

# Exibe a legenda.
plt.legend()

# Exibe uma grade.
plt.grid(alpha=0.3)

# Exibe o gráfico.
plt.show()

"""# **Interpretação do gráfico Evolução do Recall**

O Recall, também chamado de sensibilidade, mede a capacidade do modelo de identificar corretamente os casos realmente positivos. Neste projeto, a classe positiva corresponde aos casos malignos, portanto o Recall representa a proporção de mamografias realmente malignas que foram corretamente identificadas pela Rede Neural Convolucional. Essa métrica é especialmente importante na detecção de câncer de mama, pois um Recall baixo indica maior quantidade de falsos negativos, ou seja, casos malignos classificados incorretamente como benignos.



---



No gráfico de evolução do Recall, o conjunto de treinamento apresentou crescimento relativamente gradual, passando de aproximadamente 55% para 65%. Já o conjunto de validação apresentou grandes oscilações entre as épocas, indicando que o modelo ainda estava instável em relação aos dados não utilizados diretamente no treinamento. Em algumas épocas o Recall de validação chegou a 100%, porém esse resultado não significa necessariamente um modelo perfeito, pois pode ocorrer quando a rede classifica uma quantidade excessiva de exemplos como malignos. Por esse motivo, o Recall deve ser analisado em conjunto com métricas como Precision, Accuracy, AUC e matriz de confusão. Como o treinamento apresentado foi realizado com apenas cinco épocas para fins de teste, será necessário um treinamento mais longo para avaliar a estabilidade e o desempenho final da CNN.

# 21. Avaliação no conjunto de teste

O teste será feito somente após o treinamento.

Isso é importante porque o conjunto de teste deve funcionar como uma simulação de dados não vistos.

Além das métricas pedidas no enunciado, serão calculadas:

- Precision;
- Specificity;
- ROC-AUC;
- Average Precision.

## Métrica mais importante neste problema

Em detecção de câncer, o **Recall (sensibilidade)** merece atenção especial.

Um falso negativo significa que uma mamografia maligna foi classificada como benigna. Em um sistema de apoio diagnóstico, esse tipo de erro é especialmente crítico.

A Accuracy continua sendo informativa, mas não deve ser analisada isoladamente.

Nesta etapa é realizada a avaliação final da CNN no conjunto de teste, que contém imagens que não foram utilizadas para treinar o modelo. Isso é importante porque o teste funciona como uma simulação de dados novos, permitindo verificar se a rede realmente aprendeu padrões que podem ser generalizados para mamografias não vistas anteriormente.

Primeiro, o código carrega o melhor modelo salvo durante o treinamento pelo ModelCheckpoint. Em seguida, o modelo utiliza predict() para gerar, para cada mamografia do conjunto de teste, uma probabilidade de malignidade entre 0 e 1. Depois é aplicado um limiar de 0.50: probabilidades menores que 0,50 são classificadas como benignas e probabilidades maiores ou iguais a 0,50 são classificadas como malignas.

Com as previsões prontas, o código compara as classes previstas com os rótulos verdadeiros e calcula diversas métricas. A Accuracy representa a proporção total de acertos. A Precision indica, entre os exames classificados como malignos, quantos realmente eram malignos. O Recall ou Sensibilidade mostra, entre todos os casos realmente malignos, quantos foram identificados corretamente pela CNN. Essa é uma das métricas mais importantes no problema, pois um Recall baixo significa maior quantidade de falsos negativos, ou seja, casos malignos classificados incorretamente como benignos.

Também é calculado o F1-score, que combina Precision e Recall em uma única métrica e ajuda a avaliar o equilíbrio entre essas duas medidas. A ROC-AUC avalia a capacidade geral da rede de separar casos benignos e malignos considerando diferentes limiares de decisão, utilizando diretamente as probabilidades produzidas pela CNN.

A partir da matriz de confusão, o código obtém os valores de verdadeiros negativos, falsos positivos, falsos negativos e verdadeiros positivos. Com essas informações também é calculada a Specificity ou Especificidade, que representa a capacidade do modelo de reconhecer corretamente os casos benignos. Enquanto o Recall avalia principalmente a capacidade de detectar malignidade, a especificidade avalia a capacidade de identificar corretamente os negativos.

Por fim, é calculada a Average Precision, uma métrica relacionada à curva Precision-Recall e especialmente útil quando existe algum desbalanceamento entre as classes. Ao final da execução, todas essas métricas são exibidas para permitir uma avaliação mais completa do comportamento da CNN.

Para este problema, a Accuracy não deve ser analisada isoladamente. É especialmente importante observar o Recall e a quantidade de falsos negativos, pois classificar uma mamografia maligna como benigna representa um erro crítico em um possível sistema de apoio ao diagnóstico.
"""

# Carrega do disco o melhor modelo salvo durante o treinamento.
model = tf.keras.models.load_model(
    CAMINHO_MELHOR_MODELO
)

# Calcula as probabilidades previstas para todas as imagens do conjunto de teste.
probabilidades = model.predict(
    test_ds,
    verbose=1
).ravel()

# Define o limiar padrão utilizado para converter probabilidade em classe.
LIMIAR = 0.50

# Converte probabilidades maiores ou iguais ao limiar em classe maligna.
predicoes = (
    probabilidades >= LIMIAR
).astype(int)

# Obtém os rótulos verdadeiros do conjunto de teste.
y_true = test_df["label"].values

# Calcula a acurácia.
accuracy = accuracy_score(
    y_true,
    predicoes
)

# Calcula a precisão.
precision = precision_score(
    y_true,
    predicoes,
    zero_division=0
)

# Calcula o recall ou sensibilidade.
recall = recall_score(
    y_true,
    predicoes,
    zero_division=0
)

# Calcula o F1-score.
f1 = f1_score(
    y_true,
    predicoes,
    zero_division=0
)

# Calcula a ROC-AUC usando as probabilidades, e não as classes finais.
auc = roc_auc_score(
    y_true,
    probabilidades
)

# Calcula a matriz de confusão garantindo a ordem 0 e 1.
matriz = confusion_matrix(
    y_true,
    predicoes,
    labels=[0, 1]
)

# Separa os quatro valores da matriz de confusão.
tn, fp, fn, tp = matriz.ravel()

# Calcula a especificidade, que mede a proporção de benignos corretamente reconhecidos.
specificity = tn / (tn + fp) if (tn + fp) > 0 else 0.0

# Calcula a Average Precision, útil em classificação com possível desbalanceamento.
average_precision = average_precision_score(
    y_true,
    probabilidades
)

# Exibe a acurácia.
print(f"Accuracy: {accuracy:.4f}")

# Exibe a precisão.
print(f"Precision: {precision:.4f}")

# Exibe o recall.
print(f"Recall / Sensibilidade: {recall:.4f}")

# Exibe o F1-score.
print(f"F1-score: {f1:.4f}")

# Exibe a especificidade.
print(f"Specificity: {specificity:.4f}")

# Exibe a ROC-AUC.
print(f"ROC-AUC: {auc:.4f}")

# Exibe a Average Precision.
print(f"Average Precision: {average_precision:.4f}")

"""# **Resumo real do desempenho da Rede Neural Convolucional**

Na avaliação final realizada sobre o conjunto de teste, composto por 399 mamografias não utilizadas diretamente no treinamento da rede, a CNN apresentou Accuracy de aproximadamente 56,9%, Recall de 58,4%, Precision de 48,5%, F1-score de 53,0%, Especificidade de 55,8% e ROC-AUC de 59,5%. Entre os 166 casos realmente malignos, aproximadamente 97 foram corretamente identificados, enquanto cerca de 69 foram classificados incorretamente como benignos, caracterizando falsos negativos. Como o Recall mede a capacidade de identificar os casos malignos, esse resultado demonstra que o modelo ainda apresenta limitações importantes para o problema proposto. A ROC-AUC de aproximadamente 0,60 demonstra capacidade discriminativa superior ao acaso, porém ainda baixa para uma aplicação prática. Esses resultados devem ser considerados preliminares, pois o experimento foi realizado com apenas cinco épocas para validação rápida do pipeline. Para o treinamento final, será utilizado um número maior de épocas, permitindo avaliar se a rede consegue alcançar maior capacidade de generalização e, principalmente, reduzir a quantidade de falsos negativos.
"""

# Exibe um relatório detalhado com métricas para as duas classes.
print(
    classification_report(
        y_true,
        predicoes,
        target_names=["BENIGNO", "MALIGNO"],
        digits=4,
        zero_division=0
    )
)

"""
# 22. Matriz de confusão

Na matriz:

- **TN**: benignos corretamente classificados como benignos;
- **FP**: benignos classificados incorretamente como malignos;
- **FN**: malignos classificados incorretamente como benignos;
- **TP**: malignos corretamente classificados como malignos.

Para este problema, os **FN — falsos negativos** são particularmente importantes.
"""

# Cria um objeto para desenhar a matriz de confusão.
display_matriz = ConfusionMatrixDisplay(
    confusion_matrix=matriz,
    display_labels=["BENIGNO", "MALIGNO"]
)

# Desenha a matriz de confusão.
display_matriz.plot(
    values_format="d"
)

# Define o título do gráfico.
plt.title("Matriz de confusão - conjunto de teste")

# Exibe o gráfico.
plt.show()

"""# **Interpretação da Matriz de Confusão**
A matriz de confusão permite analisar detalhadamente os acertos e erros realizados pela Rede Neural Convolucional no conjunto de teste. No experimento foram identificados 130 verdadeiros negativos, correspondentes a casos benignos corretamente classificados como benignos, e 97 verdadeiros positivos, representando casos malignos corretamente identificados pelo modelo. Também foram observados 103 falsos positivos, nos quais mamografias benignas foram classificadas como malignas, e 69 falsos negativos, correspondentes a casos malignos classificados incorretamente como benignos. Os falsos negativos possuem especial importância neste problema, pois representam situações em que um possível câncer não foi identificado pelo modelo. Dessa forma, a matriz demonstra que a CNN ainda apresenta quantidade significativa de erros nas duas classes, reforçando a necessidade de um treinamento mais longo e de melhorias antes de qualquer possibilidade de utilização prática. Como este experimento foi realizado com apenas cinco épocas para validação rápida do pipeline, os resultados ainda são considerados preliminares.

# 23. Curva ROC

A curva ROC analisa diferentes limiares de classificação.

Uma ROC-AUC próxima de:

- **0,5** indica desempenho semelhante ao acaso;
- **1,0** indica excelente separação entre as classes.

Ela complementa as métricas calculadas no limiar fixo de 0,5.
"""

# Calcula os falsos positivos, verdadeiros positivos e limiares da curva ROC.
fpr, tpr, thresholds_roc = roc_curve(
    y_true,
    probabilidades
)

# Cria uma figura para a curva ROC.
plt.figure(figsize=(7, 6))

# Desenha a curva ROC do modelo.
plt.plot(
    fpr,
    tpr,
    label=f"CNN - AUC = {auc:.3f}"
)

# Desenha a linha de referência de um classificador aleatório.
plt.plot(
    [0, 1],
    [0, 1],
    linestyle="--",
    label="Aleatório"
)

# Define o texto do eixo horizontal.
plt.xlabel("Taxa de falsos positivos")

# Define o texto do eixo vertical.
plt.ylabel("Taxa de verdadeiros positivos / Recall")

# Define o título do gráfico.
plt.title("Curva ROC")

# Exibe a legenda.
plt.legend()

# Exibe uma grade.
plt.grid(alpha=0.3)

# Exibe o gráfico.
plt.show()

"""# **Interpretação da Curva ROC**
A curva ROC é utilizada para avaliar a capacidade do modelo de diferenciar casos benignos e malignos considerando diferentes limiares de classificação. O eixo vertical representa a taxa de verdadeiros positivos, equivalente ao Recall ou Sensibilidade, enquanto o eixo horizontal representa a taxa de falsos positivos. A linha diagonal tracejada corresponde ao desempenho esperado de um classificador aleatório e serve como referência para comparação. No experimento realizado, a CNN apresentou uma ROC-AUC de aproximadamente 0,595, indicando desempenho superior ao acaso, porém ainda com baixa capacidade de separação entre as classes. Como a curva permanece relativamente próxima da linha aleatória, o resultado reforça que o modelo ainda necessita de maior treinamento e possíveis ajustes para melhorar sua capacidade de discriminar mamografias benignas e malignas. Como o treinamento analisado foi realizado com apenas cinco épocas, esse resultado deve ser considerado preliminar.

# 24. Curva Precision-Recall

A curva Precision-Recall é especialmente útil quando existe desbalanceamento entre as classes.

Ela mostra o compromisso entre:

- detectar mais casos malignos;
- manter boa precisão nas previsões positivas.
"""

# Calcula os pontos da curva Precision-Recall.
precisoes_curva, recalls_curva, thresholds_pr = precision_recall_curve(
    y_true,
    probabilidades
)

# Cria uma figura para a curva Precision-Recall.
plt.figure(figsize=(7, 6))

# Desenha a curva Precision-Recall.
plt.plot(
    recalls_curva,
    precisoes_curva,
    label=f"Average Precision = {average_precision:.3f}"
)

# Define o texto do eixo horizontal.
plt.xlabel("Recall")

# Define o texto do eixo vertical.
plt.ylabel("Precision")

# Define o título do gráfico.
plt.title("Curva Precision-Recall")

# Exibe a legenda.
plt.legend()

# Exibe uma grade.
plt.grid(alpha=0.3)

# Exibe o gráfico.
plt.show()

"""# **Interpretação do gráfico Curva Precision Recall**
A curva Precision-Recall permite avaliar o equilíbrio entre a capacidade do modelo de detectar casos malignos e a confiabilidade dessas previsões. O Recall representa a proporção de casos realmente malignos identificados corretamente pela CNN, enquanto a Precision indica, entre os casos classificados como malignos, quantos realmente eram malignos. Ao variar o limiar de classificação, geralmente existe um compromisso entre essas métricas: aumentar o Recall pode fazer com que mais casos malignos sejam detectados, porém também pode aumentar os falsos positivos e reduzir a Precision. No experimento realizado, a Average Precision foi de aproximadamente 0,495, indicando que o modelo ainda apresenta desempenho limitado nesse equilíbrio. Como o treinamento utilizado foi de apenas cinco épocas, o resultado é preliminar e poderá melhorar com um treinamento mais completo.

# 25. Análise dos falsos negativos

Como o recall é uma métrica crítica neste contexto, vamos identificar especificamente os casos malignos que o modelo classificou como benignos.

Esses exemplos devem ser discutidos no relatório, pois demonstram as limitações do modelo.
"""

# Cria uma cópia do conjunto de teste para armazenar as previsões.
resultados_df = test_df.copy()

# Adiciona a probabilidade prevista de malignidade.
resultados_df["probabilidade_maligno"] = probabilidades

# Adiciona a classe prevista utilizando o limiar escolhido.
resultados_df["predicao"] = predicoes

# Seleciona somente imagens realmente malignas que foram previstas como benignas.
falsos_negativos_df = resultados_df[
    (resultados_df["label"] == 1) &
    (resultados_df["predicao"] == 0)
].copy()

# Ordena os falsos negativos da menor para a maior probabilidade de malignidade.
falsos_negativos_df = falsos_negativos_df.sort_values(
    "probabilidade_maligno"
)

# Exibe a quantidade total de falsos negativos.
print("Quantidade de falsos negativos:", len(falsos_negativos_df))

# Exibe algumas informações dos primeiros falsos negativos.
display(
    falsos_negativos_df[
        [
            "patient_id",
            "tipo_lesao",
            "probabilidade_maligno",
            "image_path_abs"
        ]
    ].head(10)
)

"""# **Considerações sobre os Falsos Negativos**

Nesta etapa são analisados especificamente os falsos negativos produzidos pela Rede Neural Convolucional. Um falso negativo ocorre quando uma mamografia realmente maligna é classificada incorretamente como benigna pelo modelo. Para realizar essa análise, são selecionados os casos cujo rótulo verdadeiro é maligno, mas cuja previsão ficou abaixo do limiar utilizado para classificação. No experimento foram identificados 69 falsos negativos. Esses casos são particularmente importantes no contexto da detecção de câncer de mama, pois representam situações em que o modelo deixou de reconhecer uma condição maligna. A análise individual desses erros permite compreender melhor as limitações da CNN e pode auxiliar na identificação de padrões de imagens ou tipos de lesão que apresentam maior dificuldade para o modelo. Como o treinamento realizado até o momento foi curto, esses resultados ainda são preliminares.
"""